# -*- coding: utf-8 -*-
"""data_cleaning.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16akc8zpLLEBJN-KraxtwN_wjQ_cdN7Qc

Load Text
"""

from google.colab import files
filename = files.upload()

file = open('metamorphosis_clean.txt','rt')
text = file.read()
file.close()

"""Split Into Words"""

import nltk
nltk.download('punkt')
nltk.download('stopwords')

from nltk.tokenize import word_tokenize
tokens = word_tokenize(text)
print(tokens)

"""Covert to Lowercase"""

tokens = [w.lower() for w in tokens]
print(tokens)

"""Remove Punctuation"""

import string
table = str.maketrans('','',string.punctuation)
stripped = [w.translate(table) for w in tokens]
print(stripped)

"""Removing Non-alphabetic Tokens"""

words = [word for word in stripped if word.isalpha()]
print(words)

"""Filter Out Stopwords"""

from nltk.corpus import stopwords
stop_words = set(stopwords.words('english'))
words = [w for w in words if not w in stop_words]
print(words)