# -*- coding: utf-8 -*-
"""Hypothesis_Testing_Demo_DataLit_Week_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/aztecman/DataLit/blob/master/Hypothesis_Testing_Demo_DataLit_Week_2.ipynb

## Hypothesis Testing Demo

### School of AI - DataLit Week 2

#### Any mistakes made here are the sole property of I, Carson Bentley

This notebook is based on an article provided by Gaël Varoquaux as part of the [scipy documentation](http://scipy-lectures.org/packages/statistics/index.html#hypothesis-testing-comparing-two-groups).

See the following for a description of how the data was collected:

[Brain Size and Intelligence. Willerman et al. (1991)](https://www3.nd.edu/~busiforc/handouts/Data%20and%20Stories/correlation/Brain%20Size/brainsize.html)
"""

import pandas as pd

URL = 'http://scipy-lectures.org/_downloads/brain_size.csv'

df = pd.read_csv(URL, sep=';', na_values=".", index_col=0)

df.head(12)

df.describe()

from scipy import stats

"""Check out the source code for scipy.stats [here](https://github.com/scipy/scipy/blob/master/scipy/stats/stats.py). Under the hood, scipy uses numpy for the math calculations.

### One Sample T-Test

I'm curious if the averages given by this sample vary from the standard average IQ, which I happen to know is 100. In this experiment the null hypothesis is that the population from which this sample is drawn is actually 100, and the alternative hypothesis is that it is not.

Let's use 5% as our significance, alpha
"""

IQ_column_names = ['FSIQ', 'VIQ', 'PIQ']

for IQ_column in IQ_column_names:
  print(stats.ttest_1samp(df[IQ_column], 100))

"""Since the p-value is smaller than alpha, we can confidently reject the null hypothesis. That means that our average IQs of 113, 112, and 111 (for the FSIQ, VIQ, and PIQ) are most likely due to something other than random variation.

Speculating as to why these IQs are above average, I imagined a scenario in which subjects are being gathered for a data collection at a university. Many of these subjects would naturally be students.

As it turns out, this speculation was correct, as you can confirm by looking at the article linked at the top of this notebook.

### Two Sample T-Test

Suppose we want to compare the IQs of men and women.
"""

groupby_gender = df.groupby('Gender')
for IQ_column in IQ_column_names:
  for gender, value in groupby_gender[IQ_column]:
    print((gender, value.mean()))

"""Although the males in this sample have higher average IQs in the three areas tested, these results are not necessarily significant.

Let's do a two sample t-test to see if any of these differences meet a 5% standard alpha.
"""

female = df[df['Gender'] == 'Female']
male = df[df['Gender'] == 'Male']
for IQ_column in IQ_column_names:
  print(stats.ttest_ind(female[IQ_column], male[IQ_column]))

"""Since all three p-values are greater than 5%, we fail to reject the null hypothesis in each case. In other words the difference in mean IQ values for the observed data is not statistically significant."""